[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies.clap]
version = "4.5.20"
features = ["cargo"]

[lib]
name = "bin"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"
